const UUID={service:'000055ff-0000-1000-8000-00805f9b34fb',write:'000033f1-0000-1000-8000-00805f9b34fb',notify:'000033f2-0000-1000-8000-00805f9b34fb',service5:'000056ff-0000-1000-8000-00805f9b34fb',write5:'000034f1-0000-1000-8000-00805f9b34fb',notify5:'000034f2-0000-1000-8000-00805f9b34fb'};
let device=null,server=null,writeChar=null,notifyChar=null,lines=[];
const $=id=>document.getElementById(id); const hex=b=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join(' ').toUpperCase();
function log(s){const t=new Date().toLocaleTimeString();lines.push(`[${t}] ${s}`);if(lines.length>1000)lines.shift();$('log').textContent=lines.join('\n');$('log').scrollTop=$('log').scrollHeight}
function setConnected(v){$('connect').disabled=v;$('disconnect').disabled=!v;['readBattery','readHr','readSteps'].forEach(id=>$(id).disabled=!v);$('status').textContent=v?'Подключено':'Не подключено';}
function findChar(service, uuid){try{return service.getCharacteristic(uuid)}catch(e){return null}}
async function connect(){if(!navigator.bluetooth){log('Web Bluetooth недоступен. Используй Chrome на Android в HTTPS.');return}try{device=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[UUID.service,UUID.service5,'battery_service']});device.addEventListener('gattserverdisconnected',()=>{log('GATT отключён');server=null;writeChar=null;notifyChar=null;setConnected(false)});$('deviceName').textContent=device.name||'(без имени)';log(`Выбрано устройство: ${device.name||'(без имени)'}`);server=await device.gatt.connect();$('gatt').textContent='connected';let services=await server.getPrimaryServices();log(`Найдено сервисов: ${services.length}`);for(const s of services){log(`SERVICE ${s.uuid}`);let chars=await s.getCharacteristics();for(const c of chars)log(`  CHAR ${c.uuid} props=${[...c.properties].join(',')}`)}let svc=null;for(const id of [UUID.service,UUID.service5]){try{svc=await server.getPrimaryService(id);if(svc)break}catch(e){}}if(svc){writeChar=findChar(svc,svc.uuid===UUID.service5?UUID.write5:UUID.write);notifyChar=findChar(svc,svc.uuid===UUID.service5?UUID.notify5:UUID.notify);if(!writeChar)writeChar=(await svc.getCharacteristics()).find(c=>c.properties.write||c.properties.writeWithoutResponse);if(!notifyChar)notifyChar=(await svc.getCharacteristics()).find(c=>c.properties.notify||c.properties.indicate);if(notifyChar){await notifyChar.startNotifications();notifyChar.addEventListener('characteristicvaluechanged',onNotify);log(`Уведомления включены: ${notifyChar.uuid}`)}else log('Notify characteristic не найден');}else log('Известный GloryFit service не найден — смотри список выше.');setConnected(true)}catch(e){log(`ОШИБКА: ${e.message}`);setConnected(false)}}
function onNotify(ev){const v=ev.target.value;const h=hex(v.buffer);log(`RX ${h}`);const a=new Uint8Array(v.buffer);if(a[0]===0xE5&&a.length>8){const hr=a[8];if(hr>=40&&hr<=200){$('hr').textContent=hr+' bpm';log(`  → предполагаемый HR: ${hr} bpm`)}}}
async function send(bytes,label){if(!writeChar){log('Write characteristic не найден');return}try{await writeChar.writeValue(new Uint8Array(bytes));log(`TX ${label}: ${hex(bytes)}`)}catch(e){log(`TX ERROR ${e.message}`)}}
$('connect').onclick=connect;$('disconnect').onclick=()=>{if(device?.gatt?.connected)device.gatt.disconnect()};$('readBattery').onclick=()=>send([0xA2],'A2');$('readHr').onclick=()=>send([0xE5,0x00],'E5 00');$('readSteps').onclick=()=>send([0xB2,0xFA],'B2 FA');$('clear').onclick=()=>{lines=[];$('log').textContent='Очищено.'};$('export').onclick=()=>{const blob=new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kw66-ble-log-'+Date.now()+'.txt';a.click();URL.revokeObjectURL(a.href)};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(e=>log('SW: '+e.message)));if(!window.isSecureContext)log('Внимание: Web Bluetooth требует HTTPS (или localhost).');
