"use strict";
const UUID={service4:"000055ff-0000-1000-8000-00805f9b34fb",service5:"000056ff-0000-1000-8000-00805f9b34fb",rx4:"000033f2-0000-1000-8000-00805f9b34fb",rx5:"000034f2-0000-1000-8000-00805f9b34fb",rxAlt:"0000b004-0000-1000-8000-00805f9b34fb",battery:"00002a19-0000-1000-8000-00805f9b34fb"};
const $=id=>document.getElementById(id); const hex=b=>[...b].map(x=>x.toString(16).padStart(2,"0").toUpperCase()).join(" ");
let device=null,server=null,rxChars=[],buffers={},recording=false,rows=[],raw=[],lastD1=null,counts={"07":0,"08":0,"09":0};
function ts(d=new Date()){return d.toLocaleTimeString('ru-RU',{hour12:false})+'.'+String(d.getMilliseconds()).padStart(3,'0')}
function log(s){$('last').textContent+=($('last').textContent?"\n":"")+'['+ts()+'] '+s;$('last').scrollTop=$('last').scrollHeight}
function setState(s,run=false){$('state').textContent=s;$('state').className='pill'+(run?' run':'')}
function label(u){u=u.toLowerCase();return u===UUID.rx4?'BLE4':u===UUID.rx5?'BLE5':u===UUID.rxAlt?'ALT':u}
function props(c){let p=c.properties||{};return Object.keys(p).filter(k=>p[k]).join(',')}
async function subscribe(c){await c.startNotifications();c.addEventListener('characteristicvaluechanged',e=>{let v=e.target.value,b=new Uint8Array(v.buffer.slice(v.byteOffset,v.byteOffset+v.byteLength));onRX(b,c.uuid)})}
async function connect(){if(!navigator.bluetooth){log('Web Bluetooth недоступен. Открой PWA в Chrome на Android.');return}try{log('Поиск устройства…');device=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[UUID.service4,UUID.service5,UUID.battery]});device.addEventListener('gattserverdisconnected',()=>{server=null;rxChars=[];buffers={};setState('отключено');$('device').textContent='Отключено';log('GATT disconnected.')});server=await device.gatt.connect();$('device').textContent=`Выбрано: ${device.name||'(без имени)'} (${device.id})`;log('GATT connected.');let chars=[];for(const s of await server.getPrimaryServices())for(const c of await s.getCharacteristics()){chars.push(c);log(`CHAR ${c.uuid} [${props(c)}]`)}rxChars=chars.filter(c=>[UUID.rx4,UUID.rx5,UUID.rxAlt].includes(c.uuid.toLowerCase())&&(c.properties?.notify||c.properties?.indicate));$('rxChar').textContent=rxChars.map(c=>label(c.uuid)).join(', ')||'не найден';for(const c of rxChars)await subscribe(c);log(`RX каналов: ${rxChars.length}`)}catch(e){log(`ОШИБКА: ${e.name||'Error'}: ${e.message||e}`)}}
function expected(b){if(!b.length)return null; if(b[0]===0xD1)return 2; if(b[0]===0xA2)return 2; if(b[0]===0xA3)return 8; if(b[0]===0xF7)return 11; if(b[0]===0xB1)return 18; return null}
function onRX(b,uuid){raw.push({t:new Date().toISOString(),source:label(uuid),hex:hex(b)});if(raw.length>1000)raw.shift();if(recording){$('raw').textContent=raw.slice(-300).map(x=>`[${x.t.slice(11,23)}] ${x.source} ${x.hex}`).join('\n');$('raw').scrollTop=$('raw').scrollHeight}let key=uuid.toLowerCase(),prev=buffers[key]||new Uint8Array(0),m=new Uint8Array(prev.length+b.length);m.set(prev);m.set(b,prev.length);buffers[key]=m;flush(key,uuid)}
function flush(key,uuid){let b=buffers[key]||new Uint8Array(0);while(b.length){let n=expected(b);if(n===null){let idx=-1;for(let i=1;i<b.length;i++)if([0xD1,0xA2,0xA3,0xB1,0xF7].includes(b[i])){idx=i;break}if(idx>0){b=b.slice(idx);continue}break}if(b.length<n)break;let p=b.slice(0,n);b=b.slice(n);if(p[0]===0xD1)onD1(p,uuid)}buffers[key]=b}
function onD1(p,uuid){let code=p[1].toString(16).padStart(2,'0').toUpperCase(),now=Date.now(),delta=lastD1===null?null:now-lastD1;lastD1=now;if(counts[code]!==undefined)counts[code]++;$('d1count').textContent=counts['07']+counts['08']+counts['09'];$('c07').textContent=counts['07'];$('c08').textContent=counts['08'];$('c09').textContent=counts['09'];$('delta').textContent=delta===null?'—':delta+' ms';let names={'07':'PLAY/PAUSE','08':'NEXT','09':'PREVIOUS'};let action=names[code]||'0x'+code;let marker=recording?'REC':'LIVE';log(`D1 ${code} (${action})${delta===null?'':` Δ=${delta} ms`}${recording?' [записывается]':''}`);if(recording){let r={n:rows.length+1,t:new Date().toISOString(),delta,hex:hex(p),code,action,marker};rows.push(r);renderRow(r)}}
function renderRow(r){let tr=document.createElement('tr');tr.innerHTML=`<td>${r.n}</td><td>${r.t.slice(11,23)}</td><td>${r.delta===null?'—':r.delta+' ms'}</td><td>${r.hex}</td><td>${r.action}</td><td>${r.marker}</td>`;$('rows').appendChild(tr);let sc=$('rows').parentElement;sc.scrollTop=sc.scrollHeight}
$('connect').onclick=connect;$('disconnect').onclick=()=>{try{if(device?.gatt?.connected)device.gatt.disconnect()}catch{}};
$('record').onclick=()=>{recording=true;rows=[];$('rows').innerHTML='';lastD1=null;setState('ЗАПИСЬ',true);$('record').disabled=true;$('stop').disabled=false;$('mark').disabled=false;log('=== START RECORD ===');};
$('stop').onclick=()=>{recording=false;setState('готово');$('record').disabled=false;$('stop').disabled=true;$('mark').disabled=true;log(`=== STOP RECORD: ${rows.length} D1 events ===`)};
$('mark').onclick=()=>{let r={n:'M'+(Date.now()),t:new Date().toISOString(),delta:null,hex:'—',code:'MARK',action:'РУЧНАЯ МЕТКА',marker:'MARK'};rows.push(r);renderRow(r);log('--- ручная метка ---')};
$('clear').onclick=()=>{rows=[];raw=[];$('rows').innerHTML='';$('raw').textContent='—';$('last').textContent='Ожидание D1…';counts={'07':0,'08':0,'09':0};lastD1=null;$('d1count').textContent='0';$('c07').textContent='0';$('c08').textContent='0';$('c09').textContent='0';$('delta').textContent='—'};
$('export').onclick=()=>{let data={app:'KW66 Touch Recorder',version:'1.0',device:device?.name||null,exportedAt:new Date().toISOString(),recordedEvents:rows,rawRx:raw};let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kw66-touch-recording.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
</script>
